# -*- coding: utf-8 -*-
"""codeunnati3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dMxEoIjISKqOzTUB4-IvIjt2Z_OfNRsa
"""

!pip install numpy

!pip install seaborn

!pip install pandas

#140-weight 0-bumpy 1-smooth
#0-apple 1-orange

from sklearn import tree
features = [[140,1],[130,1],[150,0],[170,0]]
labels = [0,0,1,1]
clf = tree.DecisionTreeClassifier()
clf = clf.fit(features,labels)
print(clf.predict([[140,1]]))

bejdbsawhbfakgvfcjaehgbceh jbcshbda

